document.addEventListener("DOMContentLoaded",function(){
    document.getElementById("div2").style.display="block";
    document.getElementsByTagName("button")[0].addEventListener("click",function(){
        document.getElementById("div1").classList.toggle("testdiv1");
        if(document.getElementById("div2").style.display=="block"){
            document.getElementById("div2").style.display="none";
        }
        else{
            document.getElementById("div2").style.display="block";
        }
    })
})